LOCAL_PATH := device/realme/RMX3834

PRODUCT_PLATFORM := ums9230

# API
PRODUCT_SHIPPING_API_LEVEL := 34

# Dynamic Partitions stuff
PRODUCT_USE_DYNAMIC_PARTITIONS := true

# VNDK
PRODUCT_TARGET_VNDK_VERSION := 34
